/**
 * Ant Design v5 — Method B (algorithm execution).
 *
 * Ant's palette is generated by @ant-design/colors:
 *   generate('#1677ff') → ['#e6f4ff', ..., '#001d66']
 * Ten steps, indexed 1-10 in Ant's own docs (we mirror that).
 *
 * Each named palette (blue, red, green, gold, daybreak, etc) ships
 * pre-computed in the package as a 10-entry array. The static export
 * IS the byte-faithful canonical form — we read it directly rather
 * than re-running generate(), to match what Ant itself ships.
 */

import {
  blue,
  cyan,
  geekblue,
  gold,
  green,
  lime,
  magenta,
  orange,
  purple,
  red,
  volcano,
  yellow,
  grey
} from "@ant-design/colors";

const RAMPS = { blue, cyan, geekblue, gold, green, lime, magenta, orange, purple, red, volcano, yellow, grey };

export default {
  harvestNotes:
    "Values read byte-faithfully from @ant-design/colors. Each ramp is a 10-entry hex array indexed 1-10 in Ant's own docs (step 6 = the 'solid' tone). To regenerate against a different seed, call generate('#hex') from the same library.",
  async algorithm() {
    const out = {};
    for (const [name, ramp] of Object.entries(RAMPS)) {
      ramp.forEach((hex, idx) => {
        out[`${name}.${idx + 1}`] = hex;
      });
    }
    return {
      rawValues: out,
      library: "@ant-design/colors",
      version: "8.0.1",
      inputs: "package default seeds"
    };
  },
  map(values) {
    const pick = (family) => {
      const out = {};
      for (const [k, v] of Object.entries(values)) {
        if (k.startsWith(`${family}.`)) {
          out[k.slice(family.length + 1)] = v;
        }
      }
      return out;
    };
    return {
      base: {
        blue: pick("blue"),
        red: pick("red"),
        green: pick("green"),
        gold: pick("gold"),
        orange: pick("orange"),
        purple: pick("purple"),
        cyan: pick("cyan"),
        magenta: pick("magenta"),
        grey: pick("grey"),
        white: { 0: "oklch(100% 0 0)" }
      },
      notes:
        "Ant Design canonical 10-step ramps for blue/red/green/gold/orange/purple/cyan/magenta/grey. Accent = blue.6 (daybreak), critical = red.5, success = green.6, warning = gold.6, info = blue.6 per Ant's own status-colour convention."
    };
  }
};
